# Generated by Django 5.2.6 on 2025-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=150, verbose_name="Nom du restaurant"),
                ),
                (
                    "responsable",
                    models.CharField(max_length=100, verbose_name="Nom du responsable"),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d’ajout"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client (Restaurant)",
                "verbose_name_plural": "Clients (Restaurants)",
                "ordering": ["nom"],
            },
        ),
    ]
