# Generated by Django 5.2.6 on 2025-09-24 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_produit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_commande",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de commande",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="application.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="CommandeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="application.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commande",
            },
        ),
    ]
