# Generated by Django 5.2.6 on 2025-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_commande_commandeitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commande",
            options={},
        ),
        migrations.AlterModelOptions(
            name="commandeitem",
            options={},
        ),
        migrations.AddField(
            model_name="commandeitem",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(default="En cours", max_length=20),
        ),
    ]
