# Generated by Django 5.2.6 on 2025-09-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0004_alter_commande_options_alter_commandeitem_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandeitem",
            name="prix_unitaire",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commandeitem",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commande_items",
                to="application.produit",
            ),
        ),
    ]
