# Generated by Django 5.2.6 on 2025-09-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_alter_commandeitem_prix_unitaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandeitem",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commandeitem",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.produit"
            ),
        ),
    ]
