# Generated by Django 5.2.6 on 2025-09-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_alter_commandeitem_prix_unitaire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("mois", models.PositiveIntegerField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="application.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture mensuelle",
                "verbose_name_plural": "Factures mensuelles",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("client", "annee", "mois")},
            },
        ),
        migrations.CreateModel(
            name="FactureCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.commande",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="application.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande liée à la facture",
                "verbose_name_plural": "Commandes liées aux factures",
            },
        ),
    ]
