# Generated by Django 5.2.6 on 2025-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0007_facture_facturecommande"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresMounia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_hotel", models.CharField(default="Mon app", max_length=100)),
                ("adresse", models.TextField(default="Adresse par défaut")),
                (
                    "email_contact",
                    models.EmailField(default="contact@mounia.com", max_length=254),
                ),
                (
                    "telephone_contact",
                    models.CharField(default="+123456789", max_length=20),
                ),
                (
                    "politique_annulation",
                    models.TextField(
                        default="Annulation gratuite jusqu'à 48h avant l'arrivée.",
                        help_text="Texte explicatif pour les annulations",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="hotel_logos/"),
                ),
            ],
            options={
                "verbose_name_plural": "Paramètres de mounia",
            },
        ),
        migrations.RemoveField(
            model_name="facturecommande",
            name="facture",
        ),
        migrations.RemoveField(
            model_name="facturecommande",
            name="commande",
        ),
        migrations.DeleteModel(
            name="Facture",
        ),
        migrations.DeleteModel(
            name="FactureCommande",
        ),
    ]
