# Generated by Django 5.2.6 on 2025-09-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_customuser_emailverificationtoken_loginhistory"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Les groupes auxquels cet utilisateur appartient.",
                related_name="customuser_groups",
                related_query_name="customuser",
                to="auth.group",
                verbose_name="groupes",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions spécifiques pour cet utilisateur.",
                related_name="customuser_permissions",
                related_query_name="customuser",
                to="auth.permission",
                verbose_name="permissions utilisateur",
            ),
        ),
    ]
