# Generated by Django 5.2.6 on 2025-10-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0010_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville",
                    models.CharField(max_length=100, unique=True, verbose_name="Ville"),
                ),
                (
                    "prix_livraison",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix de livraison (en €)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "ordering": ["ville"],
            },
        ),
        migrations.RemoveField(
            model_name="emailverificationtoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="loginhistory",
            name="user",
        ),
        migrations.AlterField(
            model_name="client",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="application.livraison",
                verbose_name="Ville",
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
        migrations.DeleteModel(
            name="LoginHistory",
        ),
    ]
