# Generated by Django 5.2.6 on 2025-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0011_livraison_remove_emailverificationtoken_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ville",
            field=models.CharField(max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="client",
            name="prix_livraison",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Prix de livraison (en €)",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Livraison",
        ),
    ]
