# Generated by Django 5.2.6 on 2025-10-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0012_alter_client_ville_client_prix_livraison_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="ice",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="ICE"
            ),
        ),
    ]
