# Generated by Django 5.2.6 on 2025-10-07 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0013_client_ice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
