# Generated by Django 5.2.6 on 2025-10-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0014_alter_commande_date_commande"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemiseClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_remise",
                    models.CharField(
                        choices=[
                            ("pourcentage", "Pourcentage"),
                            ("fixe", "Montant fixe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("mois_application", models.CharField(max_length=7)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "mois_application")},
            },
        ),
    ]
