# Generated by Django 5.2.6 on 2025-10-09 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0015_remiseclient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commande",
            options={
                "ordering": ["-date_commande"],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="commandeitem",
            options={
                "ordering": ["date_ajout"],
                "verbose_name": "Item de commande",
                "verbose_name_plural": "Items de commande",
            },
        ),
        migrations.AlterModelOptions(
            name="remiseclient",
            options={
                "ordering": ["-mois_application", "client"],
                "verbose_name": "Remise client",
                "verbose_name_plural": "Remises clients",
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes internes"
            ),
        ),
        migrations.AddField(
            model_name="commandeitem",
            name="date_ajout",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="actif",
            field=models.BooleanField(default=True, verbose_name="Produit actif"),
        ),
        migrations.AddField(
            model_name="remiseclient",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="remiseclient",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Description de la remise",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name="client",
            name="prix_livraison",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Prix de livraison (en MAD)",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("En cours", "En cours"),
                    ("Confirmée", "Confirmée"),
                    ("Livrée", "Livrée"),
                    ("Annulée", "Annulée"),
                ],
                default="En cours",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="remiseclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remises",
                to="application.client",
            ),
        ),
        migrations.AlterField(
            model_name="remiseclient",
            name="mois_application",
            field=models.CharField(
                help_text="Format: YYYY-MM",
                max_length=7,
                verbose_name="Mois d'application",
            ),
        ),
        migrations.AlterField(
            model_name="remiseclient",
            name="type_remise",
            field=models.CharField(
                choices=[
                    ("pourcentage", "Pourcentage (%)"),
                    ("fixe", "Montant fixe (MAD)"),
                ],
                max_length=20,
                verbose_name="Type de remise",
            ),
        ),
        migrations.AlterField(
            model_name="remiseclient",
            name="valeur_remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valeur de la remise",
            ),
        ),
    ]
