# Generated by Django 5.2.6 on 2025-10-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0016_alter_commande_options_alter_commandeitem_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("commande_jour", "Commandes du jour"),
                            ("statut", "Changement de statut"),
                            ("rapport", "Rapport quotidien"),
                            ("alerte", "Alerte importante"),
                        ],
                        default="commande_jour",
                        max_length=20,
                    ),
                ),
                ("lue", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
    ]
