# Generated by Django 5.2.6 on 2025-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0018_alter_client_adresse_alter_client_ice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ice",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="ICE"
            ),
        ),
    ]
