# Generated by Django 5.2.6 on 2025-10-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0019_alter_client_ice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.TextField(verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="responsable",
            field=models.CharField(max_length=100, verbose_name="Nom du responsable"),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                default=1, max_length=20, unique=True, verbose_name="Téléphone"
            ),
            preserve_default=False,
        ),
    ]
