# Generated by Django 5.2.6 on 2025-10-10 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0021_alter_client_ice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="ice",
        ),
    ]
