# Generated by Django 5.2.6 on 2025-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0022_remove_client_ice"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="ice",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="ICE"
            ),
        ),
    ]
