# Generated by Django 5.2.6 on 2025-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0023_client_ice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="responsable",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du responsable"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Téléphone",
            ),
        ),
    ]
