# Generated by Django 5.2.6 on 2025-10-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0024_alter_client_adresse_alter_client_responsable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.CharField(max_length=7, verbose_name="Mois (YYYY-MM)")),
                (
                    "montant_du",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant dû"
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("paye", "Payé"),
                            ("partiel", "Partiellement payé"),
                            ("non_paye", "Non payé"),
                        ],
                        default="non_paye",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="application.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-mois"],
                "unique_together": {("client", "mois")},
            },
        ),
    ]
